version: '3'

services:
  gitlab:
    image: ci-tool-stack/gitlab-ce:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.${VERSION:-latest}
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
#    environment:
##      GITLAB_ROOT_PASSWORD: mypassword
##      GITLAB_OMNIBUS_CONFIG: |
##        external_url 'http://mysite'
##        gitlab_rails['gitlab_email_display_name'] = 'Gitlab'
##        gitlab_rails['gitlab_email_from'] = 'noreply@forge.factory'
##        gitlab_rails['ldap_allow_username_or_email_login'] = true
##        gitlab_rails['ldap_base'] = 'ou=People,dc=org'
##        gitlab_rails['ldap_bind_dn'] = 'cn=admin,ou=Meta,dc=org'
##        gitlab_rails['ldap_enabled'] = true
##        gitlab_rails['ldap_host'] = 'ldaphost'
##        gitlab_rails['ldap_method'] = 'plain'
##        gitlab_rails['ldap_password'] = 'cloud'
##        gitlab_rails['ldap_port'] = '389'
##        gitlab_rails['ldap_uid'] = 'uid'
##        gitlab_rails['time_zone'] = 'Europe/Paris'
##        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "10080:80"
      - "10443:443"
      - "10022:22"
